### ISSUE TITLE
Can't recover account

### ISSUE THREAD

**Issue by gabesbit** [Coinomi/coinomi-android#21]
Hi,

First of all thanks for this nice Android multi wallet, which is truly unique of it's kind.
I have a problem restoring my wallet on a second phone. Half of the words are missing from the word suggestor. If I input my words manually, then it refuses to continue with error "passphrase contains unrecognized words". IMO that word corrector is a nice feature to prevent typos, but it should let the users continue if they whish to input custom words.

**Comment by erasmospunk** [comment]
The word list is predefined and contains exactly [2048 words](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) as of the BIP39 standard so it is impossible to have different words.

If your _recovery phrase_ contains words that are not in the list, it means that you misspelled something and then skipped verifying your _recovery phrase_ when creating your wallet (otherwise the errors would have been detected).

Not all is lost though. If you still have the other phone with the wallet, go to the `Settings -> Show recovery phrase` to view your original and correct _recovery phrase_.

If you don't have the wallet, try to guess the correct phrase by choosing words from the list that sound or are written similarly.
When you enter the _recovery phrase_, it will check if it is valid as a whole. There is a small chance that the _recovery phrase_ will be valid but is different than your original _recovery phrase_, the result will be that the restored wallet will be empty (because it wasn't your original wallet).

One last thing to keep in mind: if you enabled "Also protect my recovery phrase" when setting a password for your wallet, you *must* select "My recovery phrase is password protected" when restoring it, otherwise your wallet will be empty when restored. By default this feature is disabled.

Please tell us what finally happened so we can close this issue or further help you recovering your funds!

**Comment by gabesbit** [comment]
Thanks for explanation. You were right. I had a wrong seed written down on a paper. I was able to successfully recover my coinomi wallet from my first phone. Only mystery remains what app that wrong seed belongs to? Overtime maybe I will find out :) Thanks again. Closing.
